# Этот файл используется для определения и управления сервисами контейнеризации приложения.
#
# Сервисы:
#   db:
#     - Использует образ postgres:16-alpine для работы с PostgreSQL.
#     - Переменные окружения (POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB) передаются через env_file (.env).
#     - Том postgres_data используется для сохранения данных базы.
#     - Внешний порт, указанный в переменной DB_PORT_EXTERNAL (из .env), пробрасывается на внутренний порт 5432.
#
#   web-app:
#     - Строится из Dockerfile и запускается как контейнер с приложением Django.
#     - Зависит от сервиса db (база данных должна быть запущена до запуска приложения).
#     - Переменная DATABASE_HOST используется для указания адреса подключения к базе данных.
#
# Volumes:
#   postgres_data:
#     - Том для хранения данных PostgreSQL, чтобы данные сохранялись между перезапусками контейнера.


services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXTERNAL}:5432"


  web-app:
    build:
      context: .
    container_name: dog_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DB_HOST}

volumes:
  postgres_data:
